const TABLES = {
  users: ['id','openid','phone','nickname','avatar','role','owner_cert_status','vehicle_model','vehicle_no','bio','growth','level','credit_score','discoverable','invite_code','invited_by','created_at','updated_at','last_login_at'],
  user_settings: ['id','user_id','allow_team_message','allow_marketing','share_location','sentinel_mode','emergency_name','emergency_phone','created_at','updated_at'],
  vehicle_certifications: ['id','user_id','real_name','plate','vehicle_model','license_photo','ocr_result','liveness_token','liveness_result','status','reject_reason','reviewed_by','created_at','reviewed_at'],
  trip_drafts: ['id','user_id','start_name','start_lng','start_lat','end_name','end_lng','end_lat','depart_at','route','waypoints','note','status','converted_trip_id','created_at','updated_at'],
  badges: ['id','badge_key','name','description','icon','rule','enabled','created_at','updated_at'],
  user_badges: ['id','user_id','badge_id','awarded_at'],
  admins: ['id','account','password_hash','role','merchant_id','status','created_at','last_login_at'],
  trips: ['id','owner_id','title','team_name','start_name','start_lng','start_lat','end_name','end_lng','end_lat','route','waypoints','depart_at','days','daily_km','max_cars','current_cars','price_share','depth','plans','equipment','privacy','discoverable','status','stage','note','created_at','updated_at','completed_at'],
  trip_applications: ['id','trip_id','user_id','message','status','reviewed_by','created_at','reviewed_at'],
  trip_members: ['id','trip_id','user_id','role','status','joined_at','left_at','leave_reason','last_location_at','deviation_started_at'],
  locations: ['id','user_id','trip_id','lng','lat','speed','altitude','accuracy','bearing','reported_at','expires_at'],
  messages: ['id','conversation_type','conversation_id','sender_id','message_type','content','media_url','metadata','created_at','deleted_at'],
  conversation_members: ['id','conversation_type','conversation_id','user_id','role','unread_count','joined_at','left_at','last_read_at'],
  follows: ['id','follower_id','target_type','target_id','created_at'],
  blocks: ['id','user_id','target_user_id','created_at'],
  poi_topics: ['id','creator_id','name','location_name','lng','lat','source','event_id','status','last_message_at','archived_at','created_at'],
  poi_topic_members: ['id','topic_id','user_id','role','followed','participated','joined_at'],
  merchants: ['id','owner_user_id','name','phone','address','description','lng','lat','business_hours','license_photo','qualification_files','bank_info','status','reject_reason','level','score','commission_rate','reward_pool_enabled','rescue_enabled','rescue_services','rescue_radius_km','rescue_phone','business_open','created_at','updated_at'],
  merchant_change_requests: ['id','merchant_id','changes','status','reviewed_by','review_reason','created_at','reviewed_at'],
  products: ['id','merchant_id','name','cover_photo','photos','description','category','origin_price','tiers','stock','sold','reserved','valid_hours','max_group_size','max_quantity','status','lng','lat','address','created_at','updated_at'],
  groupbuy_sessions: ['id','product_id','creator_id','trip_id','target_people','joined_people','current_price','status','expires_at','success_at','failed_at','created_at'],
  groupbuy_members: ['id','session_id','user_id','order_id','quantity','paid_amount','status','joined_at'],
  orders: ['id','order_no','user_id','merchant_id','product_id','session_id','coupon_id','quantity','origin_amount','discount_amount','paid_amount','status','payment_provider','payment_transaction_id','verify_code','expires_at','paid_at','verified_at','verified_by','verified_lng','verified_lat','created_at','updated_at'],
  payment_events: ['id','provider_event_id','event_type','payload','processed_at','created_at'],
  refunds: ['id','order_id','user_id','reason','amount','status','provider_refund_id','reviewed_by','review_reason','created_at','reviewed_at','completed_at'],
  verification_records: ['id','order_id','merchant_id','operator_id','code','lng','lat','created_at'],
  settlements: ['id','merchant_id','order_id','period_start','period_end','gross_amount','commission_rate','commission_amount','net_amount','status','provider_id','triggered_by','created_at','completed_at'],
  coupons: ['id','owner_type','owner_id','name','type','amount','threshold_amount','discount_rate','total','issued','used','valid_days','budget_amount','status','created_at','updated_at'],
  user_coupons: ['id','coupon_id','user_id','source','source_ref','status','issued_at','expires_at','used_at','order_id','verify_code'],
  coupon_redemptions: ['id','user_coupon_id','coupon_id','merchant_id','operator_id','amount','status','provider_id','lng','lat','created_at','settled_at'],
  invites: ['id','inviter_id','invitee_id','source','source_ref','status','bound_at','first_order_at','reward_status','reward_value'],
  invite_links: ['id','inviter_id','scene','source','expires_at','created_at'],
  growth_rules: ['id','rule_key','name','points','daily_limit','enabled','updated_by','updated_at'],
  growth_logs: ['id','user_id','rule_key','delta','reason','ref_type','ref_id','created_at'],
  support_tickets: ['id','user_id','order_id','category','title','status','priority','assigned_to','created_at','updated_at','closed_at'],
  support_messages: ['id','ticket_id','sender_type','sender_id','content','media_urls','created_at'],
  notifications: ['id','user_id','type','title','content','data','priority','read_at','created_at'],
  emergency_events: ['id','user_id','trip_id','lng','lat','status','contacts_notified','team_notified','created_at','resolved_at'],
  traffic_events: ['id','provider_id','source','reporter_id','event_type','title','description','lng','lat','severity','starts_at','ends_at','status','reviewed_by','review_reason','reviewed_at','topic_id','created_at'],
  system_settings: ['id','setting_key','value','updated_by','updated_at'],
  idempotency_keys: ['id','scope','idempotency_key','response','created_at','expires_at'],
  audit_logs: ['id','actor_type','actor_id','method','path','status_code','ip','metadata','created_at']
};

const JSON_COLUMNS = new Set([
  'trips.route','trips.waypoints','trips.plans','trips.equipment','messages.metadata',
  'vehicle_certifications.ocr_result','vehicle_certifications.liveness_result',
  'merchants.qualification_files','merchants.bank_info','merchants.rescue_services','products.photos','products.tiers',
  'merchant_change_requests.changes',
  'support_messages.media_urls','notifications.data',
  'trip_drafts.route','trip_drafts.waypoints','badges.rule','payment_events.payload',
  'system_settings.value','idempotency_keys.response','audit_logs.metadata'
]);

module.exports = { TABLES, JSON_COLUMNS };
